version: "3.8"

services:
  app-example-ci-php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-example-ci-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - xdebug-data:/tmp/xdebug
    environment:
      XDEBUG_MODE: coverage
      XDEBUG_CONFIG: remote_connect_back=1 remote_port=9003 remote_enable=1 profiler_enable=0 profiler_enable_trigger=1 profiler_output_dir=/tmp/xdebug mode=debug
      APPLICATION_ENV: development
    networks:
      - network-example-ci-php

  nginx:
    image: nginx:latest
    container_name: nginx-example-ci-php
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network-example-ci-php

  sonarqube-example-ci-php:
    image: sonarqube:latest
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
      - "9000:9000"
    networks:
      - network-example-ci-php

  sonar-scanner-example-ci-php:
    image: mercuriete/sonar-scanner:latest
    depends_on:
      - sonarqube-example-ci-php
    environment:
      - SONAR_HOST_URL=http://sonar:9000
      - SONAR_PROJECT_KEY=hello:world
      - SONAR_PROJECT_NAME=example-ci-php
      - SONAR_PROJECT_VERSION=0.1
    networks:
      - network-example-ci-php

networks:
  network-example-ci-php:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  xdebug-data:
    name: xdebug-data
