version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - xdebug-data:/tmp/xdebug
    environment:
      XDEBUG_MODE: coverage
      XDEBUG_CONFIG: remote_connect_back=1 remote_port=9003 remote_enable=1 profiler_enable=0 profiler_enable_trigger=1 profiler_output_dir=/tmp/xdebug mode=debug
      APPLICATION_ENV: development
    networks:
      - app-php

  nginx:
    image: nginx:latest
    container_name: app-nginx
    ports:
      - 8888:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-php

volumes:
  xdebug-data:
    name: xdebug-data

networks:
  app-php:
    driver: bridge
